In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [3]:
df = pd.read_csv('train.csv' , usecols=['Age' , 'Pclass' , 'SibSp' , 'Parch' , 'Survived'])

In [4]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [5]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [17]:
x = df.iloc[:,1:]
y = df.iloc[: ,0]

In [18]:
x.head()

   Pclass   Age  SibSp  Parch
0       3  22.0      1      0
1       1  38.0      1      0
2       3  26.0      0      0
3       1  35.0      1      0
4       3  35.0      0      0

In [19]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [21]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy' , cv=20))

np.float64(0.6933333333333332)

# Applying Feature Construction

In [22]:
x['Family_size'] = x['SibSp'] + x['Parch'] + 1

In [23]:
x.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [24]:
def func(num):
    if num == 1:
        return 0  # alone
    elif num >1 and num <=4:
        return 1 # small family
    else:
        return 2 # large family

In [25]:
func(3)

1

In [26]:
func(5)

2

In [27]:
func(1)

0

In [28]:
x['Family_type'] = x['Family_size'].apply(func)

In [29]:
x.head()

   Pclass   Age  SibSp  Parch  Family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [31]:
x.drop(columns=['SibSp' , 'Family_size' , 'Parch'] , inplace=True)

In [32]:
x.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [33]:
np.mean(cross_val_score(LogisticRegression() , x , y , scoring='accuracy' , cv =20))

np.float64(0.7003174603174602)

# Feature Splitting

In [34]:
df = pd.read_csv('train.csv')

In [35]:
df['Title'] = df['Name'].str.split(',' , expand=True)[1].str.split('.' , expand=True)[0]

In [37]:
df[['Title' , 'Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [39]:
(df.groupby('Title')['Survived'].mean()).sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64